# Generated by Django 5.2.6 on 2025-09-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_service_delete_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonails',
            old_name='profile_image',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='testimonails',
            old_name='position',
            new_name='role',
        ),
    ]
