# Generated by Django 5.2.6 on 2025-09-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_profile_image_testimonails_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonails',
            name='external_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
