# Generated by Django 5.2.6 on 2025-11-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_testimonails_external_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonails',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='testi/'),
        ),
    ]
