# Generated by Django 5.2.6 on 2026-03-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_about_profile_image_alter_home_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonails',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
