# Generated by Django 5.2.6 on 2026-03-09 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='state',
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
