# Generated by Django 5.2.6 on 2025-09-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='external_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
