# Generated by Django 5.2.6 on 2025-09-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_external_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='external_images',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
