# Generated by Django 5.2.6 on 2026-03-09 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_image_delete_projectimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
